const translations = {
  changeLanguage: 'Language: ',
  welcomeName: 'Welcome {0}!',
  signIn: 'Sign In',
  signInGoogle: 'Sign In with Google',
  signInFacebook: 'Sign In with Facebook',
  email: 'Email',
  password: 'Password',
  forgotPassword: 'Forgot your password?',
  createAccount: 'Create an Account',
  verifyAccount: 'Verify Account',
  passwordReset: 'Password Reset',
  setNewPassword: 'Set New Password',
  createNewPassword: 'Create New Password',
  welcome: 'Welcome',
  back: 'Back',
  or: 'Or',
  incorrectLogin: 'Incorrect username or password.',
  name: 'Name',
  username: 'Username',
  confirmPassword: 'Confirm Password',
  passwordSettings: 'Your password must have the following:',
  oneUppercase: 'At least one uppercase letter',
  oneLowercase: 'At least one lowercase letter',
  oneDigit: 'At least one digit',
  oneSpecialCharacter: 'At least one special character',
  more8Characters: 'Should be more than 8 characters',
  less16Characters: 'Should be less than 16 characters',
  fillAllFields: 'Please fill in all fields.',
  validEmail: 'Please enter a valid email.',
  validEmailAccount: 'Please enter a valid email or create an account',
  here: 'here',
  passwordNotMatch: 'Passwords do not match',
  signUp: 'Sign Up',
  enterEmailAddress:
    "Enter your email address and we'll send you a code to help you reset your password.",
  sendResetCode: 'Send reset code',
  enterResetCode: 'Enter reset code',
  checkEmail: 'Please check your email',
  forResetCodeAndCreatePassword: 'for a reset code and create a new password.',
  enterCorrectResetCode: 'Please enter correct reset code.',
  reEnterPassword: 'Re-enter the password',
  updatePassword: 'Update Password',
  emailAlreadyExists: 'An account with the given email already exists.',
  checkEmailForConfirmationCode:
    'Please check your email for a confirmation code. This may take several minutes.',
  invalidVerificationCode:
    'Invalid verification code provided, please try again.',
  newVerificationCodeSentSuccesfully:
    'New verification code sent successfully.',
  enterConfirmationCode: 'Enter your confirmation code.',
  didNotReceiveCode: "Didn't receive your verification code?",
  resendCode: 'Resend Code',
  replaceTemporaryPassword:
    'Please replace your temporary password with a new password for',
  setPassword: 'Set Password',
};

export default translations;
