const translations = {
  changeLanguage: 'Language: ',
  welcomeName: 'Welcome {0}!',
  signIn: 'Sign In',
  signInGoogle: 'Sign In with Google',
  signInFacebook: 'Sign In with Facebook',
  email: 'Email',
  password: 'Password',
  forgotPassword: 'Forgot your password?',
  createAccount: 'Create an Account',
  verifyAccount: 'Verify Account',
  passwordReset: 'Password Reset',
  setNewPassword: 'Set New Password',
  createNewPassword: 'Create New Password',
  welcome: 'Welcome',
  back: 'Back',
  or: 'Or',
  incorrectLogin: 'Incorrect username or password.',
  name: 'Name',
  username: 'Username',
  confirmPassword: 'Confirm Password',
  passwordSettings: 'Your password must have the following:',
  oneUppercase: 'At least one uppercase letter',
  oneLowercase: 'At least one lowercase letter',
  oneDigit: 'At least one digit',
  oneSpecialCharacter: 'At least one special character',
  more8Characters: 'Should be more than 8 characters',
  less16Characters: 'Should be less than 16 characters',
  fillAllFields: 'Please fill in all fields.',
  validEmail: 'Please enter a valid email.',
  validEmailAccount: 'Please enter a valid email or create an account',
  here: 'here',
  passwordNotMatch: 'Passwords do not match',
  signUp: 'Sign Up',
  enterEmailAddress:
    "Enter your email address and we'll send you a code to help you reset your password.",
  sendResetCode: 'Send reset code',
  enterResetCode: 'Enter reset code',
  checkEmail: 'Please check your email',
  forResetCodeAndCreatePassword: 'for a reset code and create a new password.',
  enterCorrectResetCode: 'Please enter correct reset code.',
  reEnterPassword: 'Re-enter the password',
  updatePassword: 'Update Password',
  emailAlreadyExists: 'An account with the given email already exists.',
  checkEmailForConfirmationCode:
    'Please check your email for a confirmation code. This may take several minutes.',
  invalidVerificationCode:
    'Invalid verification code provided, please try again.',
  newVerificationCodeSentSuccesfully:
    'New verification code sent successfully.',
  enterConfirmationCode: 'Enter your confirmation code.',
  didNotReceiveCode: "Didn't receive your verification code?",
  resendCode: 'Resend Code',
  replaceTemporaryPassword:
    'Please replace your temporary password with a new password for',
  setPassword: 'Set Password',
  alertNewActionTitle: 'New Actions In Need of Validation',
  alertNewActionText: 'You have {0} actions to validate!',
  startValidating: 'Start Validating',
  alertActionsPendingTitle: '{0} Actions Pending Validation',
  alertActionsPendingText: 'The impact of your pending actions is {0} of CO2 saved',
  recentProgress: 'Recent Progress',
  logANewAction: 'Log A New Action',
  co2SavedWeek: 'CO2 Saved This Week',
  collectiveImpact: 'Collective Impact',
  myGroups: 'My Groups',
  myActions: 'My Actions',
  createNewGroup: 'Create New Group',
  globalGroups: 'Global Groups',
  globalUsers: 'Global Users',
  totalCO2Saved: 'Total CO2 Saved',
  weeklyCO2Saved: 'Weekly CO2 Saved',
  leaderboardDisplaying: 'Leaderboard displaying {tab} ranked by ',
  rank: 'Rank',
  totalCO2: 'Total CO2',
  totalPoints: 'Total Points',
  weeklyCO2: 'Weekly CO2',
  weeklyPoints: 'Weekly Points',
  totalCO2Colon: 'Total CO2:',
  totalPointsColon: 'Total Points:',
  weeklyCO2Colon: 'Weekly CO2:',
  weeklyPointsColon: 'Weekly Points:',
  leaderboards: 'Leaderboards',
  noMyGroups: 'No groups to display. Create or join a group to get started!',
  viewGroupStats: 'View Group Stats',
  myContributions: 'My Contributions',
  myContribution: 'My Contribution',
  allOtherMembers: 'All Other Members',
  joinGroup: 'Join Group',
  read: 'Read',
  more: 'More',
  less: 'Less',
  membersColon: 'Members:',
  public: 'Public',
  private: 'Private',
  leaveGroup: 'Leave Group',
  currentPlace: 'Current Place',
  labelRowsPerPage: 'Rows per page:',
  of: 'of',
  groupInfo: 'Group Info',
  memberActions: 'Member Actions',
  groupMembers: 'Group Members',
  addMembers: 'Add Members',
  editGroupInfo: 'Edit Group Info',
  about: 'About',
  groupOwners: 'Group Owners',
  view: 'View',
  noActions: 'There are currently no actions to display.',
  co2SavedColon: 'CO2 Saved:',
  totalPointsEarnedColon: 'Total Points Earned:',
  unapprove: 'Unapprove',
  promoteUserToOwner: 'Promote User to Group Owner',
  demoteUserToMember: 'Demote User to Group Member',
  removeUserFromGroup: 'Remove User From Group',
  roleColon: 'Role:',
  yourRoleColon: 'Your Role:',
  viewUserProfile: 'View User Profile',
  success: 'Success!',
  warning: 'Warning!',
  successUserNowOwner: '{0} is now a group owner',
  successUserNowMember: '{0} is now a group member',
  successUserNowRemoved: '{0} has been removed from the group',
  demotionErrorTitle: 'Demotion Error',
  demotionErrorText: 'Groups must have at least 1 group owner',
  addMembersDescription: 'Add users to this group by sending them your group link',
  addMembersDescriptionPassword: 'Add users to this group by sending them your group link and password',
  groupLinkLabel: 'Your Group Link is:',
  groupPasswordLabel: 'Your Group Password is:',
  linkCopied: 'Link Copied!',
  passwordCopied: 'Password Copied!',
  editGroupEmptyError: 'Empty group name',
  editGroupTakenError: 'Group name is taken',
  editGroupPasswordError: 'Empty password',
  groupUploadIcon: 'Upload Group Icon',
  groupNameEmptyError: 'Field must be completed',
  groupNameTakenError: 'A group already exists with the given name',
  description: 'Description',
  groupPrivacy: 'Group Privacy',
  groupPasswordEmptyError: 'Private groups must have a password',
  deleteGroup: 'Delete Group',
  saveGroupInfo: 'Save Group Info',
  join: 'Join',
  cancel: 'Cancel',
  delete: 'Delete',
  leave: 'Leave',
  groupUpdatedMsg: 'The group has been updated',
  groupDeletedMsg: '{0} has been deleted!',
  homepageRedirectMsg: 'You will now be directed to the homepage',
  deleteGroupPrompt: 'Delete {0}',
  deletePrompAlert: 'This is irreversible',
  logout: 'Logout',
  leaveGroupLastMemberWarning: 'This group will be deleted since there will be no group members.',
  promoteOtherUserBeforeLeavingGroup: 'You must promote another user to group owner before leaving the group.',
  removeGroupOwner: 'Remove Group Owner',
  promoteOtherUserBeforeRemovingUser: 'You must promote another user to group owner before removing this user.',
  leftGroup: 'You have left the the group!',
  joinGroupAlreadyMember: 'You are already a member of this group!',
  joinGroupTitle: 'You have been invited to join {0}',
  successRedirectProfilePage: "Success! Redirecting to {0}'s profile page",
  joinGroupConfirm: 'Please confirm by selecting Join.',
  joinGroupSelectCancel: 'Select Cancel to be redirected to the group page.',
  joinGroupEnterPassword: 'To join this group, please enter the group password and select Join.',
  incorrectPassword: 'Incorrect Password',
  logAction: 'Log Action',
  dashboard: 'Dashboard',
  findGroup: 'Find Group',
  createGroup: 'Create Group',
  validateActions: 'Validate Actions',
  adminDashboard: 'Admin Dashboard',
  myAccount: 'My Account',
  logActionTitle: 'Log New Action',
  logActionStep1: 'Select Action',
  logActionStep2: 'Select Dates',
  logActionStep3: 'Action Fact',
  logActionStep4: 'Action Items',
  logActionStep5: 'Validation',
  logActionStep6: 'Bonus Question',
  logActionStep7: 'CO2 Saved',
  next: 'Next',
  previous: 'Previous',
  chooseDate: 'Choose Date',
  mustBeNumber: 'Input must be a number or decimal greater than 0',
  imageValidationText: 'Please upload an image related to your action item for verification',
  imageValidationDimensions: 'Minimum dimensions 100x100 px',
  imageValidationError: 'This Is Not An Image File',
  imageValidationSelected: 'Image Selected!',
  imageValidationDrop: 'Drop Your Image Here, Or',
  browse: 'Browse',
  uploadImage: 'Upload Image',
  skip: 'Skip',
  actionFactResponse: 'Thank you for submitting an action!',
  actionFactAllFacts: 'You have viewed all the facts for this action',
  bonusQuizChoicesLabel: 'Answer Choices',
  bonusQuizSubmit: 'Submit Quiz',
  bonusQuizSkip: 'Skip Quiz',
  correct: 'Correct!',
  incorrect: 'Incorrect!',
  finish: 'Finish',
  tryAgain: 'Try Again',
  co2SavedScreenState: 'Your action is currently being',
  submitted: 'submitted',
  validated: 'validated',
  co2SavedScreenSkip: 'Press skip to view validation results at a later time',
  thankYou: 'Thank you!',
  co2SavedScreenValidated: 'Your action has been validated',
  co2SavedScreenSaved: 'You have saved {0} g of CO2',
  co2SavedScreenApproval: 'Your action is awaiting admin approval',
  co2SavedScreenImpact: 'The impact of your action is {0} g of CO2 saved',
  co2SavedScreenAnother: 'Add Another Action',
  createGroupTitle: 'Create New Group',
  uploadGroupIcon: 'Upload Group Icon',
  groupName: 'Group Name',
  groupDescription: 'Group Description',
  redirectGroupPage: 'You will now be redirected to the group page',
  nameC: 'Name:',
  emailC: 'Email:',
  editInfo: 'Edit Info',
  loggedActions: 'Logged Actions',
  awaitingValidation: 'Awaiting Validation',
  notPassValidation: 'Did Not Pass Validation',
  noValidatedActions: 'There are no validated actions to show',
  noUnvalidatedActions: 'There are no unvalidated actions to show',
  noFailedActions: 'There are no failed actions to show',
  editAccountInfoTitle: 'Edit Account Information',
  uploadProfilePhoto: 'Upload Profile Photo',
  requiredFieldsMessage: 'Please fill out all required fields',
  saveNameEmailPhoto: 'Save Name, Email, Photo',
  changePassword: 'Change Password',
  currentPassword: 'Current Password',
  currentPasswordMessage: 'Current password is incorrect',
  newPassword: 'New Password',
  confirmNewPassword: 'Confirm New Password',
  passwordsDontMatch: 'Passwords do not match.',
  savePassword: 'Save Password',
  toggleCurrentPassword: 'toggle current password visibility',
  toggleNewPassword: 'toggle new password visibility',
  toggleConfirmNewPassword: 'toggle confirm new password visibility',
  findGroupTitle: 'Search For A Group',
  findGroupDescription: 'Enter the group name of any public group',
  findGroupErrorSearch: 'Your search for "{0}" did not match any public groups',
  findGroupTopGroups: 'Here are the top 5 public groups who you may want to be a part of',
  searchResults: 'Search results',
  validateActionsUsersWithoutGroupsTab: 'Users Without Groups',
  validateActionsAllUnvalidatedActionsTab: 'All Unvalidated Actions',
  searchByC: 'Search By:',
  actionName: 'Action Name',
  search: 'Search',
  groupNameSearchEmptySearch: 'Your search for "{0}" did not match any of your groups',
  groupNameSearchNoGroups: 'You currently do not own any groups',
  filteringBy: 'Filtering By:',
  currentFilter: 'Current filter',
  changeFilter: 'Change filter',
  groupNameSearchAllFilter: 'All My Groups',
  validateActionsNoActions: 'There are no actions in need of validation',
  actionNameSearchAllFilter: 'All Action Types',
  actionNameSearchEmptySearch: 'Your search for "{0}" did not match any action type names',
  actionNameSearchNoActions: 'There are currently no action types',
  submittedInC: 'Submitted in:',
  accept: 'Accept',
  reject: 'Reject',
  actions: 'Actions',
  clearSearch: 'Clear Search',
  totalUsers: 'Total Users',
  totalGroups: 'Total Groups',
  actionsSubmitted: 'Actions Submitted',
  actionsSubmittedFilter: 'Actions submitted during the past {0}',
  allTimeStats: 'All Time Stats',
  totalActionsSubmitted: 'Total Number of Actions Submitted',
  actionsFirstAnswerCorrect: 'Actions With First Quiz Answer Correct',
  actionsFirstAnswerIncorrect: 'Actions With First Quiz Answer Incorrect',
  actionsSubmittedWithImage: 'Actions Submitted With Image',
  actionsSubmittedWithoutImage: 'Actions Submitted Without Image',
  numberActionsSubmittedWithImage: 'Number of Actions Submitted With Image',
  numberActionsSubmittedWithoutImage: 'Number of Actions Submitted Without Image',
  date: 'Date',
  gramsCO2Saved: 'Grams CO2 Saved',
  applyFilter: 'Apply Filter',
  createAction: 'Create Action',
  manageActions: 'Manage Actions',
  manageQuizQuestions: 'Manage Quiz Questions',
  sevenDays: '7 Days',
  thirtyDays: '30 Days',
  ninetyDays: '90 Days',
  oneYear: 'Year',
  co2SavedDuring: 'CO2 Saved during the past {0}',
  userNoteGroupOwner: ' (Owner)',
};

export default translations;
