const translations = {
  changeLanguage: 'Idioma: ',
  welcomeName: '¡Bienvenido {0}!',
  signIn: 'Ingresar',
  signInGoogle: 'Iniciar sesión con Google',
  signInFacebook: 'Iniciar sesión con Facebook',
  email: 'Correo electrónico',
  password: 'Correo electrónico',
  forgotPassword: '¿Olvidaste tu contraseña?',
  createAccount: 'Crear una cuenta',
  verifyAccount: 'Crear una cuenta',
  passwordReset: 'Restablecer la contraseña',
  setNewPassword: 'Establecer nueva contraseña',
  createNewPassword: 'Crear nueva contraseña',
  welcome: 'Bienvenido',
  back: 'Atras',
  or: 'O',
  incorrectLogin: 'Nombre de usuario o contraseña incorrectos.',
  name: 'Nombre',
  username: 'Nombre de usuario',
  confirmPassword: 'Confirmar contraseña',
  passwordSettings: 'Su contraseña debe tener lo siguiente:',
  oneUppercase: 'Al menos una letra mayúscula',
  oneLowercase: 'Al menos una letra mayúscula',
  oneDigit: 'Al menos un dígito',
  oneSpecialCharacter: 'Al menos un carácter especial',
  more8Characters: 'Debe tener más de 8 caracteres',
  less16Characters: 'Debe tener menos de 16 caracteres',
  fillAllFields: 'Por favor complete todos los campos.',
  validEmail: 'Por favor ingrese un correo electrónico válido.',
  validEmailAccount: 'Ingrese un correo electrónico válido o cree una cuenta',
  here: 'aquí',
  passwordNotMatch: 'Las contraseñas no coinciden',
  signUp: 'Registrarse',
  enterEmailAddress:
    'Ingrese su dirección de correo electrónico y le enviaremos un código para ayudar a restablecer su contraseña.',
  sendResetCode: 'Enviar código de reinicio',
  enterResetCode: 'Ingrese el código de reinicio',
  checkEmail: 'Por favor revise su correo electrónico',
  forResetCodeAndCreatePassword:
    'para restablecer el código y crear una nueva contraseña.',
  enterCorrectResetCode: 'Por favor, ingrese el código de reinicio correcto.',
  reEnterPassword: 'Vuelva a ingresar la contraseña',
  updatePassword: 'Actualizar contraseña',
  emailAlreadyExists:
    'Ya existe una cuenta con el correo electrónico indicado.',
  checkEmailForConfirmationCode:
    'Revise su correo electrónico para obtener un código de confirmación. Esto puede demorar varios minutos.',
  invalidVerificationCode:
    'Código de verificación proporcionado no válido, inténtalo de nuevo.',
  newVerificationCodeSentSuccesfully:
    'Nuevo código de verificación enviado con éxito.',
  enterConfirmationCode: 'Nuevo código de verificación enviado con éxito.',
  didNotReceiveCode: '¿No recibiste tu código de verificación?',
  resendCode: 'Reenviar código',
  replaceTemporaryPassword:
    'Reemplace su contraseña temporal con una nueva contraseña para',
  setPassword: 'Establecer contraseña',
  alertNewActionTitle: 'Nuevas acciones que necesitan validación',
  alertNewActionText: '¡Tienes {0} acciones para validar!',
  startValidating: 'Comenzar a validar',
  alertActionsPendingTitle: '{0} acciones pendientes de validación',
  alertActionsPendingText: 'El impacto de sus acciones pendientes es {0} de CO2 ahorrado',
  recentProgress: 'Progreso reciente',
  logANewAction: 'Registrar una nueva acción',
  co2SavedWeek: 'CO2 ahorrado esta semana',
  collectiveImpact: 'Impacto colectivo',
  myGroups: 'Mis Grupos',
  createNewGroup: 'Crear nuevo grupo',
  globalGroups: 'Grupos globales',
  globalUsers: 'Usuarios globales',
  totalCO2Saved: 'CO2 total ahorrado',
  weeklyCO2Saved: 'CO2 ahorrado semanalmente',
  leaderboardDisplaying: 'Tabla de clasificación que muestra {tab} clasificada por',
  rank: 'Rango',
  totalCO2: 'CO2 Total',
  totalPoints: 'Puntos Totales',
  weeklyCO2: 'CO2 Semanal',
  weeklyPoints: 'Puntos Semanales',
  totalCO2Colon: 'CO2 Total:',
  totalPointsColon: 'Puntos Totales:',
  weeklyCO2Colon: 'CO2 Semanal:',
  weeklyPointsColon: 'Puntos Semanales:',
  leaderboards: 'Tablas de clasificación',
  noMyGroups: 'No hay grupos para mostrar. ¡Crea o únete a un grupo para comenzar!',
  viewGroupStats: 'Ver estadísticas del grupo',
  myContributions: 'Mis contribuciones',
  myContribution: 'Mi Contribución',
  allOtherMembers: 'Todos los demás miembros',
  joinGroup: 'Unirse al grupo',
  read: 'Leer',
  more: 'Más',
  less: 'Menos',
};

export default translations;
