const translations = {
  changeLanguage: 'Idioma: ',
  welcomeName: '¡Bienvenido {0}!',
  signIn: 'Ingresar',
  signInGoogle: 'Iniciar sesión con Google',
  signInFacebook: 'Iniciar sesión con Facebook',
  email: 'Correo electrónico',
  password: 'Contraseña',
  forgotPassword: '¿Olvidaste tu contraseña?',
  createAccount: 'Crear una cuenta',
  verifyAccount: 'Crear una cuenta',
  passwordReset: 'Restablecer la contraseña',
  setNewPassword: 'Establecer nueva contraseña',
  createNewPassword: 'Crear nueva contraseña',
  welcome: 'Bienvenido',
  back: 'Atras',
  or: 'O',
  incorrectLogin: 'Nombre de usuario o contraseña incorrectos.',
  name: 'Nombre',
  username: 'Nombre de usuario',
  confirmPassword: 'Confirmar contraseña',
  passwordSettings: 'Su contraseña debe tener lo siguiente:',
  oneUppercase: 'Al menos una letra mayúscula',
  oneLowercase: 'Al menos una letra mayúscula',
  oneDigit: 'Al menos un dígito',
  oneSpecialCharacter: 'Al menos un carácter especial',
  more8Characters: 'Debe tener más de 8 caracteres',
  less16Characters: 'Debe tener menos de 16 caracteres',
  fillAllFields: 'Por favor complete todos los campos.',
  validEmail: 'Por favor ingrese un correo electrónico válido.',
  validEmailAccount: 'Ingrese un correo electrónico válido o cree una cuenta',
  here: 'aquí',
  passwordNotMatch: 'Las contraseñas no coinciden',
  signUp: 'Registrarse',
  enterEmailAddress:
    'Ingrese su dirección de correo electrónico y le enviaremos un código para ayudar a restablecer su contraseña.',
  sendResetCode: 'Enviar código de reinicio',
  enterResetCode: 'Ingrese el código de reinicio',
  checkEmail: 'Por favor revise su correo electrónico',
  forResetCodeAndCreatePassword:
    'para restablecer el código y crear una nueva contraseña.',
  enterCorrectResetCode: 'Por favor, ingrese el código de reinicio correcto.',
  reEnterPassword: 'Vuelva a ingresar la contraseña',
  updatePassword: 'Actualizar contraseña',
  emailAlreadyExists:
    'Ya existe una cuenta con el correo electrónico indicado.',
  checkEmailForConfirmationCode:
    'Revise su correo electrónico para obtener un código de confirmación. Esto puede demorar varios minutos.',
  invalidVerificationCode:
    'Código de verificación proporcionado no válido, inténtalo de nuevo.',
  newVerificationCodeSentSuccesfully:
    'Nuevo código de verificación enviado con éxito.',
  enterConfirmationCode: 'Nuevo código de verificación enviado con éxito.',
  didNotReceiveCode: '¿No recibiste tu código de verificación?',
  resendCode: 'Reenviar código',
  replaceTemporaryPassword:
    'Reemplace su contraseña temporal con una nueva contraseña para',
  setPassword: 'Establecer contraseña',
  alertNewActionTitle: 'Nuevas acciones que necesitan validación',
  alertNewActionText: '¡Tienes {0} acciones para validar!',
  startValidating: 'Comenzar a validar',
  alertActionsPendingTitle: '{0} acciones pendientes de validación',
  alertActionsPendingText:
    'El impacto de sus acciones pendientes es {0} de CO2 ahorrado',
  recentProgress: 'Progreso reciente',
  logANewAction: 'Registrar una nueva acción',
  co2SavedWeek: 'CO2 ahorrado esta semana',
  collectiveImpact: 'Impacto colectivo',
  myGroups: 'Mis Grupos',
  myActions: 'Mis Acciones',
  createNewGroup: 'Crear nuevo grupo',
  globalGroups: 'Grupos globales',
  globalUsers: 'Usuarios globales',
  totalCO2Saved: 'CO2 total ahorrado',
  weeklyCO2Saved: 'CO2 ahorrado semanalmente',
  leaderboardDisplaying:
    'Tabla de clasificación que muestra {tab} clasificada por ',
  rank: 'Rango',
  totalCO2: 'CO2 Total',
  totalPoints: 'Puntos Totales',
  weeklyCO2: 'CO2 Semanal',
  weeklyPoints: 'Puntos Semanales',
  totalCO2Colon: 'CO2 Total:',
  totalPointsColon: 'Puntos Totales:',
  weeklyCO2Colon: 'CO2 Semanal:',
  weeklyPointsColon: 'Puntos Semanales:',
  leaderboards: 'Tablas de clasificación',
  noMyGroups:
    'No hay grupos para mostrar. ¡Crea o únete a un grupo para comenzar!',
  viewGroupStats: 'Ver estadísticas del grupo',
  myContributions: 'Mis contribuciones',
  myContribution: 'Mi Contribución',
  allOtherMembers: 'Todos los demás miembros',
  joinGroup: 'Unirse al grupo',
  read: 'Leer',
  more: 'Más',
  less: 'Menos',
  membersColon: 'Miembros:',
  public: 'Público',
  private: 'Privado',
  leaveGroup: 'Abandonar grupo',
  currentPlace: 'Lugar actual',
  labelRowsPerPage: 'Filas por página:',
  of: 'de',
  groupInfo: 'Información del grupo',
  memberActions: 'Acciones del miembro',
  groupMembers: 'Miembros del grupo',
  addMembers: 'Añadir miembros',
  editGroupInfo: 'Editar información del grupo',
  about: 'Acerca de',
  groupOwners: 'Propietarios del grupo',
  view: 'Ver',
  noActions: 'Actualmente no hay acciones que mostrar.',
  co2SavedColon: 'CO2 ahorrado:',
  totalPointsEarnedColon: 'Puntos totales ganados:',
  unapprove: 'Desaprobar',
  promoteUserToOwner: 'Promover usuario a propietario del grupo',
  demoteUserToMember: 'Degradar usuario a miembro del grupo',
  removeUserFromGroup: 'Eliminar usuario del grupo',
  roleColon: 'Rol:',
  yourRoleColon: 'Tu rol:',
  viewUserProfile: 'Ver perfil de usuario',
  success: '¡Éxito!',
  warning: 'Advertencia!',
  successUserNowOwner: '{0} ahora es propietario del grupo',
  successUserNowMember: '{0} ahora es miembro del grupo',
  successUserNowRemoved: '{0} ha sido eliminado del grupo',
  demotionErrorTitle: 'Error de degradación',
  demotionErrorText: 'Los grupos deben tener al menos 1 propietario del grupo',
  addMembersDescription:
    'Agrega usuarios a este grupo enviándoles el enlace de tu grupo',
  addMembersDescriptionPassword:
    'Agrega usuarios a este grupo enviándoles el enlace y la contraseña de tu grupo',
  groupLinkLabel: 'Tu enlace de grupo es:',
  groupPasswordLabel: 'Tu contraseña de grupo es:',
  linkCopied: '¡Enlace copiado!',
  passwordCopied: '¡Contraseña copiada!',
  editGroupEmptyError: 'El nombre del grupo no puede estar vacío',
  editGroupTakenError: 'El nombre del grupo ya está en uso',
  editGroupPasswordError: 'La contraseña no puede estar vacía',
  groupUploadIcon: 'Cargar icono del grupo',
  groupNameEmptyError: 'Este campo debe ser completado',
  groupNameTakenError: 'Ya existe un grupo con el nombre ingresado',
  description: 'Descripción',
  groupPrivacy: 'Privacidad del grupo',
  groupPasswordEmptyError: 'Los grupos privados deben tener una contraseña',
  deleteGroup: 'Eliminar grupo',
  saveGroupInfo: 'Guardar información del grupo',
  join: 'Unirse',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  leave: 'Salir',
  groupUpdatedMsg: 'El grupo ha sido actualizado',
  groupDeletedMsg: '¡{0} ha sido eliminado!',
  homepageRedirectMsg: 'Serás redirigido a la página principal',
  deleteGroupPrompt: 'Eliminar {0}',
  deletePrompAlert: 'Esto es irreversible',
  logout: 'Cerrar sesión',
  leaveGroupLastMemberWarning:
    'Este grupo se eliminará ya que no habrá más miembros en el grupo.',
  promoteOtherUserBeforeLeavingGroup:
    'Debes promover a otro usuario a propietario del grupo antes de dejar el grupo.',
  removeGroupOwner: 'Eliminar propietario de grupo',
  promoteOtherUserBeforeRemovingUser:
    'Debes promover a otro usuario a propietario del grupo antes de eliminar a este usuario.',
  leftGroup: '¡Has abandonado el grupo!',
  joinGroupAlreadyMember: '¡Ya eres miembro de este grupo!',
  joinGroupTitle: 'Has sido invitado a unirte a {0}',
  successRedirectProfilePage:
    '¡Éxito! Redirigiendo a la página de perfil de {0}',
  joinGroupConfirm: 'Confirma seleccionando Unirse.',
  joinGroupSelectCancel:
    'Seleccione Cancelar para ser redirigido a la página del grupo.',
  joinGroupEnterPassword:
    'Para unirte a este grupo, ingresa la contraseña del grupo y selecciona Unirse.',
  incorrectPassword: 'Contraseña incorrecta',
  logAction: 'Registrar Acción',
  dashboard: 'Panel',
  findGroup: 'Buscar Grupo',
  createGroup: 'Crear Grupo',
  validateActions: 'Validar Acciones',
  adminDashboard: 'Panel de Administrador',
  myAccount: 'Mi Cuenta',
  logActionTitle: 'Registrar Nueva Acción',
  logActionStep1: 'Seleccionar Acción',
  logActionStep2: 'Seleccionar Fechas',
  logActionStep3: 'Datos de la Acción',
  logActionStep4: 'Validación',
  logActionStep5: 'Pregunta Extra',
  logActionStep6: 'CO2 Ahorrado',
  next: 'Siguiente',
  previous: 'Anterior',
  chooseDate: 'Elegir Fecha',
  mustBeNumber: 'El valor debe ser un número decimal mayor que 0',
  imageValidationText:
    'Por favor sube una imagen relacionada con el elemento de tu acción para su verificación',
  imageValidationDimensions: 'Dimensiones mínimas 100x100 px',
  imageValidationError: 'Esto no es un archivo de imagen',
  imageValidationSelected: '¡Imagen Seleccionada!',
  imageValidationDrop: 'Arrastra tu imagen aquí, o',
  browse: 'Navegar',
  uploadImage: 'Subir Imagen',
  skip: 'Saltar',
  actionFactResponse: '¡Gracias por enviar una acción!',
  actionFactAllFacts: 'Has visto todos los datos para esta acción',
  bonusQuizChoicesLabel: 'Opciones de respuesta',
  bonusQuizSubmit: 'Enviar Quiz',
  bonusQuizSkip: 'Saltar Quiz',
  bonusQuiz: 'Extra Quiz',
  correct: 'Correcto!',
  incorrect: 'Incorrecto!',
  finish: 'Finalizar',
  tryAgain: 'Intentar de nuevo',
  co2SavedScreenState: 'Tu acción está siendo actualmente',
  submitted: 'enviada',
  validated: 'validada',
  co2SavedScreenSkip:
    'Presiona saltar para ver los resultados de validación en otro momento',
  thankYou: '¡Gracias!',
  co2SavedScreenValidated: 'Tu acción ha sido validada',
  co2SavedScreenSaved: 'Has ahorrado {0} g de CO2',
  co2SavedScreenApproval:
    'Tu acción está pendiente de aprobación del administrador',
  co2SavedScreenImpact: 'El impacto de tu acción es {0} g de CO2 ahorrado',
  co2SavedScreenAnother: 'Agregar Otra Acción',
  createGroupTitle: 'Crear nuevo grupo',
  uploadGroupIcon: 'Subir ícono del grupo',
  groupName: 'Nombre del grupo',
  groupDescription: 'Descripción del grupo',
  redirectGroupPage: 'Serás redirigido a la página del grupo',
  nameC: 'Nombre:',
  emailC: 'Correo electrónico:',
  editInfo: 'Editar información',
  loggedActions: 'Acciones registradas',
  awaitingValidation: 'Esperando validación',
  notPassValidation: 'No pasó la validación',
  noValidatedActions: 'No hay acciones validadas para mostrar',
  noUnvalidatedActions: 'No hay acciones por validar para mostrar',
  noFailedActions: 'No hay acciones fallidas para mostrar',
  editAccountInfoTitle: 'Editar información de la cuenta',
  uploadProfilePhoto: 'Subir foto de perfil',
  requiredFieldsMessage: 'Por favor, completa todos los campos requeridos',
  saveNameEmailPhoto: 'Guardar nombre, correo electrónico y foto',
  changePassword: 'Cambiar contraseña',
  currentPassword: 'Contraseña actual',
  currentPasswordMessage: 'La contraseña actual es incorrecta',
  newPassword: 'Nueva contraseña',
  confirmNewPassword: 'Confirmar nueva contraseña',
  passwordsDontMatch: 'Las contraseñas no coinciden',
  savePassword: 'Guardar contraseña',
  toggleCurrentPassword: 'alternar visibilidad de la contraseña actual',
  toggleNewPassword: 'alternar visibilidad de la nueva contraseña',
  toggleConfirmNewPassword:
    'alternar visibilidad de la confirmación de la nueva contraseña',
  findGroupTitle: 'Buscar grupo',
  findGroupDescription:
    'Ingresa el nombre del grupo para buscar grupos públicos',
  findGroupErrorSearch:
    'Tu búsqueda de "{0}" no coincide con ningún grupo público',
  findGroupTopGroups:
    'Estos son los 5 grupos públicos más populares a los que podrías unirte',
  searchResults: 'Resultados de búsqueda',
  validateActionsUsersWithoutGroupsTab: 'Usuarios sin grupo',
  validateActionsAllUnvalidatedActionsTab: 'Todas las acciones sin validar',
  searchByC: 'Buscar por:',
  actionName: 'Nombre de la acción',
  search: 'Buscar',
  groupNameSearchEmptySearch:
    'Tu búsqueda de "{0}" no coincide con ningún grupo que posees',
  groupNameSearchNoGroups: 'Actualmente no posees ningún grupo',
  filteringBy: 'Filtrando por:',
  sortingBy: 'Ordenar por',
  changeSortingOrder: 'Cambiar el orden de clasificación',
  groupNameSearchAllFilter: 'Todos mis grupos',
  validateActionsNoActions: 'No hay acciones que necesiten validación',
  actionNameSearchAllFilter: 'Todos los tipos de acciones',
  actionNameSearchEmptySearch:
    'Tu búsqueda de "{0}" no coincide con ningún nombre de tipo de acción',
  actionNameSearchNoActions: 'Actualmente no hay tipos de acciones',
  submittedInC: 'Enviado en:',
  accept: 'Aceptar',
  reject: 'Rechazar',
  actions: 'Acciones',
  totalUsers: 'Usuarios Totales',
  totalGroups: 'Grupos Totales',
  actionsSubmitted: 'Acciones Enviadas',
  actionsSubmittedFilter: 'Acciones enviadas durante los últimos {0}',
  allTimeStats: 'Estadísticas de Todos los Tiempos',
  totalActionsSubmitted: 'Número Total de Acciones Enviadas',
  actionsFirstAnswerCorrect:
    'Acciones con la Primera Respuesta Correcta en el Quiz',
  actionsFirstAnswerIncorrect:
    'Acciones con la Primera Respuesta Incorrecta en el Quiz',
  actionsSubmittedWithImage: 'Acciones Enviadas con Imagen',
  actionsSubmittedWithoutImage: 'Acciones Enviadas sin Imagen',
  numberActionsSubmittedWithImage: 'Número de Acciones Enviadas con Imagen',
  numberActionsSubmittedWithoutImage: 'Número de Acciones Enviadas sin Imagen',
  date: 'Fecha',
  gramsCO2Saved: 'Gramos de CO2 Ahorrados',
  applyFilter: 'Aplicar Filtro',
  createAction: 'Crear Acción',
  manageActions: 'Gestionar Acciones',
  manageQuizQuestions: 'Gestionar Preguntas de Quiz',
  sevenDays: '7 Días',
  thirtyDays: '30 Días',
  ninetyDays: '90 Días',
  oneYear: 'Año',
  co2SavedDuring: 'CO2 Ahorrado durante los últimos {0}',
  userNoteGroupOwner: ' (el dueño)',
  totalGramsSavedCO2PerDayAllActions:
    'Total de Gramos de CO2 Ahorrados por Día Para Todas las Acciones',
};

export default translations;
