const translations = {
	changeLanguage: "Idioma: ",
	welcomeName: "¡Bienvenido {0}!",
	signIn: "Ingresar",
	signInGoogle: "Iniciar sesión con Google",
	email: "Correo electrónico",
	password: "Correo electrónico",
	forgotPassword: "¿Olvidaste tu contraseña?",
	createAccount: "Crear una cuenta",
	verifyAccount: "Crear una cuenta",
	passwordReset: "Restablecer la contraseña",
	setNewPassword: "Establecer nueva contraseña",
	createNewPassword: "Crear nueva contraseña",
	welcome: "Bienvenido",
	back: "Atras",
	or: "O",
	incorrectLogin: "Nombre de usuario o contraseña incorrectos.",
	name: "Nombre",
	username: "Nombre de usuario",
	confirmPassword: "Confirmar contraseña",
	passwordSettings: "Su contraseña debe tener lo siguiente:",
	oneUppercase: "Al menos una letra mayúscula",
	oneLowercase: "Al menos una letra mayúscula",
	oneDigit: "Al menos un dígito",
	oneSpecialCharacter: "Al menos un carácter especial",
	more8Characters: "Debe tener más de 8 caracteres",
	less16Characters: "Debe tener menos de 16 caracteres",
	fillAllFields: "Por favor complete todos los campos.",
	validEmail: "Por favor ingrese un correo electrónico válido.",
	validEmailAccount: "Ingrese un correo electrónico válido o cree una cuenta",
	here: "aquí",
	passwordNotMatch: "Las contraseñas no coinciden",
	signUp: "Registrarse",
	enterEmailAddress: "Ingrese su dirección de correo electrónico y le enviaremos un código para ayudar a restablecer su contraseña.",
	sendResetCode: "Enviar código de reinicio",
	enterResetCode: "Ingrese el código de reinicio",
	checkEmail: "Por favor revise su correo electrónico",
	forResetCodeAndCreatePassword: "para restablecer el código y crear una nueva contraseña.",
	enterCorrectResetCode: "Por favor, ingrese el código de reinicio correcto.",
	reEnterPassword: "Vuelva a ingresar la contraseña",
	updatePassword: "Actualizar contraseña",
	emailAlreadyExists: "Ya existe una cuenta con el correo electrónico indicado.",
	checkEmailForConfirmationCode: "Revise su correo electrónico para obtener un código de confirmación. Esto puede demorar varios minutos.",
	invalidVerificationCode: "Código de verificación proporcionado no válido, inténtalo de nuevo.",
	newVerificationCodeSentSuccesfully: "Nuevo código de verificación enviado con éxito.",
	enterConfirmationCode: "Nuevo código de verificación enviado con éxito.",
	didNotReceiveCode: "¿No recibiste tu código de verificación?",
	resendCode: "Reenviar código",
	replaceTemporaryPassword: "Reemplace su contraseña temporal con una nueva contraseña para",
	setPassword: "Establecer contraseña",
};

export default translations;