const translations = {
  changeLanguage: 'Langue: ',
  welcomeName: 'Bienvenue {0} !',
  signIn: 'Se Connecter',
  signInGoogle: 'Se connecter avec Google',
  signInFacebook: 'Se connecter avec Facebook',
  email: 'Email',
  password: 'Mot de passe',
  forgotPassword: 'Mot de passe oublié?',
  createAccount: 'Créer un compte',
  verifyAccount: 'Vérifier le compte',
  passwordReset: 'Réinitialisation du mot de passe',
  setNewPassword: 'Définir un nouveau mot de passe',
  createNewPassword: 'Créer un nouveau mot de passe',
  welcome: 'Bienvenue',
  back: 'Retour',
  or: 'Ou',
  incorrectLogin: "Nom d'utilisateur ou mot de passe incorrect.",
  name: 'Nom',
  username: "Nom d'utilisateur",
  confirmPassword: 'Confirmer le mot de passe',
  passwordSettings: 'Votre mot de passe doit avoir les éléments suivants :',
  oneUppercase: 'Au moins une lettre majuscule',
  oneLowercase: 'Au moins une lettre minuscule',
  oneDigit: 'Au moins un chiffre',
  oneSpecialCharacter: 'Au moins un caractère spécial',
  more8Characters: 'Doit comporter plus de 8 caractères',
  less16Characters: 'Doit comporter moins de 16 caractères',
  fillAllFields: 'Veuillez remplir tous les champs.',
  validEmail: 'Veuillez entrer une adresse email valide.',
  validEmailAccount:
    'Veuillez entrer une adresse email valide ou créer un compte',
  here: 'ici',
  passwordNotMatch: 'Les mots de passe ne correspondent pas',
  signUp: "S'inscrire",
  enterEmailAddress:
    'Entrez votre adresse email et nous vous enverrons un code pour vous aider à réinitialiser votre mot de passe.',
  sendResetCode: 'Envoyer le code de réinitialisation',
  enterResetCode: 'Entrez le code de réinitialisation',
  checkEmail: 'Veuillez vérifier votre email',
  forResetCodeAndCreatePassword:
    'pour un code de réinitialisation et créer un nouveau mot de passe.',
  enterCorrectResetCode: 'Veuillez entrer le code de réinitialisation correct.',
  reEnterPassword: 'Re-saisir le mot de passe',
  updatePassword: 'Mettre à jour le mot de passe',
  emailAlreadyExists: "Un compte avec l'email fourni existe déjà.",
  checkEmailForConfirmationCode:
    'Veuillez vérifier votre email pour un code de confirmation. Cela peut prendre plusieurs minutes.',
  invalidVerificationCode:
    'Code de vérification fourni invalide, veuillez réessayer.',
  newVerificationCodeSentSuccesfully:
    'Nouveau code de vérification envoyé avec succès.',
  enterConfirmationCode: 'Entrez votre code de confirmation.',
  didNotReceiveCode: "N'avez-vous pas reçu votre code de vérification?",
  resendCode: 'Renvoyer le code',
  replaceTemporaryPassword:
    'Veuillez remplacer votre mot de passe temporaire par un nouveau mot de passe pour',
  setPassword: 'Définir le mot de passe',
  alertNewActionTitle: 'Nouvelles actions nécessitant une validation',
  alertNewActionText: 'Vous avez {0} actions à valider !',
  startValidating: 'Commencer la validation',
  alertActionsPendingTitle: '{0} actions en attente de validation',
  alertActionsPendingText: 'L’impact de vos actions en attente est de {0} de CO2 économisés',
  recentProgress: 'Progrès récents',
  logANewAction: 'Enregistrer une nouvelle action',
  co2SavedWeek: 'CO2 économisé cette semaine',
  collectiveImpact: 'Impact collectif',
  myGroups: 'Mes groupes',
  createNewGroup: 'Créer un nouveau groupe',
  globalGroups: 'Groupes globaux',
  globalUsers: 'Utilisateurs globaux',
  totalCO2Saved: 'CO2 total économisé',
  weeklyCO2Saved: 'CO2 économisés hebdomadaires',
  leaderboardDisplaying: 'Tableau affichant les {tab} premiers classés par ',
  rank: 'Rang',
  totalCO2: 'Total CO2',
  totalPoints: 'Total de points',
  weeklyCO2: 'CO2 hebdomadaire',
  weeklyPoints: 'Points hebdomadaires',
  totalCO2Colon: 'Total CO2 :',
  totalPointsColon: 'Total de points :',
  weeklyCO2Colon: 'CO2 hebdomadaire :',
  weeklyPointsColon: 'Points hebdomadaires :',
  leaderboards: 'Classements',
  noMyGroups: 'Aucun groupe à afficher. Créez ou rejoignez un groupe pour commencer !',
  viewGroupStats: 'Voir les statistiques du groupe',
  myContributions: 'Mes contributions',
  myContribution: 'Ma contribution',
  allOtherMembers: 'Tous les autres membres',
  joinGroup: 'Rejoindre le groupe',
  read: 'Lire',
  more: 'Plus',
  less: 'Moins',
};

export default translations;
