name: React App CI
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Configure environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install NPM
        run: mv mock-aws-exports.txt aws-exports.js
        run: npm ci
      - name: Test with coverage
        run: npm run test:coverage
