name: React App CI
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure environment
        uses: actions/checkout@v3
      - name: Install NPM
        run: npm ci
      - name: Test with coverage
        run: npm run test:coverage
